config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :home, only: [:index] do
    collection do
      post :upload_photo
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord

  has_attached_file :avatar, 
                    :default_url => "/assets/missing.jpeg"

  validates_attachment_content_type :avatar, 
                                    :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # landing method
	def index
    @photo = Photo.new
    @photos = Photo.all
  end

  # upload phot from here
  def upload_photo
    photo = Photo.new(photo_params)
    if photo.save
      flash[:success] = "Photo upload successfully."
    else
      flash[:danger] = "Something went wrong"
    end
    redirect_to root_path
  end

  private
  # permit parameters
  def photo_params
    params.require(:photo).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :danger then "alert alert-danger"
      when :alert then "alert alert-error"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_photo_list.html.erb
<div class="row">
  <center><h1></h1></center>
  <% @photos.each do |photo| %>
    <div class="col-md-4 col-sm-6">
      <div class="inner-6">
         <div class="content">
          <h4><%= photo.avatar_file_name %><span>*</span></h4>
        </div>  
        <div class="img-box">
          <%= image_tag photo.avatar.url %>
        </div>
       
      </div>  
    </div> 
  <% end %>
</div>

app/views/home/index.html.erb
<div class="inner-contaier">
  <div class="top-section">
    <h1><center>Replace with <span>any nice</span></center></h1>
    <p>A fast and easy way to capture your claim photos and documents!</p>
    <div class="border-box">
      <div class="border-box-half"></div>
    </div>
  </div>
  <div class="image-details">
    <p>Claim No: 2</p>
    <p>Arslan Ahmad</p>
    <h1>Photo upload/Capture</h1>
  </div>
  <div class="image-box-wrapper">
    <div class="col-md-12">

      <!-- layouts show -->
      <%= render 'photo_list' %>
      <!-- layouts show end-->

      <!-- Upload form -->
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-4 col-md-6">
          
          <%= form_for @photo, :url => upload_photo_home_index_path, :html => { class: "upload-photo" } do |form| %>
              <div class="fileUpload">
                <span class="custom-span">+</span>
                <p class="custom-para">Add Images</p>
                
                <%= form.file_field :avatar, id: 'file_browse', class: 'upload' %>
              </div>

          <% end %>
        </div>
      </div>
      <!-- Upload form end -->
    </div>
  </div>
  <div class="terms-box">
    <label class="check">I agree the <a href="#">Terms & Conditions</a>
      <input type="checkbox" checked="checked">
      <span class="checkmark"></span>
    </label>
    <button class="btn btn-submit">Send</button>
  </div>
</div>

<%= javascript_include_tag "home.js" %>

app/views/layouts/_footer.html.erb
<footer class="text-center">
	<p>Copy &copy; 2018. All Right Reserved. </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <center>Clame photo capture</center>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoImageUpload</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
          <div class="<%= flash_class(key.to_sym) %>">
            <%= value %>
          </div>
        <% end %>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>